/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the ObservationScopesParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObservationScopesParam{}

// ObservationScopesParam Optional parameters that control how retain tags feed observation scopes.
type ObservationScopesParam struct {
	TagKeyWhitelist []string `json:"tag_key_whitelist,omitempty"`
}

// NewObservationScopesParam instantiates a new ObservationScopesParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObservationScopesParam() *ObservationScopesParam {
	this := ObservationScopesParam{}
	return &this
}

// NewObservationScopesParamWithDefaults instantiates a new ObservationScopesParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObservationScopesParamWithDefaults() *ObservationScopesParam {
	this := ObservationScopesParam{}
	return &this
}

// GetTagKeyWhitelist returns the TagKeyWhitelist field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ObservationScopesParam) GetTagKeyWhitelist() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.TagKeyWhitelist
}

// GetTagKeyWhitelistOk returns a tuple with the TagKeyWhitelist field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ObservationScopesParam) GetTagKeyWhitelistOk() ([]string, bool) {
	if o == nil || IsNil(o.TagKeyWhitelist) {
		return nil, false
	}
	return o.TagKeyWhitelist, true
}

// HasTagKeyWhitelist returns a boolean if a field has been set.
func (o *ObservationScopesParam) HasTagKeyWhitelist() bool {
	if o != nil && !IsNil(o.TagKeyWhitelist) {
		return true
	}

	return false
}

// SetTagKeyWhitelist gets a reference to the given []string and assigns it to the TagKeyWhitelist field.
func (o *ObservationScopesParam) SetTagKeyWhitelist(v []string) {
	o.TagKeyWhitelist = v
}

func (o ObservationScopesParam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObservationScopesParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.TagKeyWhitelist != nil {
		toSerialize["tag_key_whitelist"] = o.TagKeyWhitelist
	}
	return toSerialize, nil
}

type NullableObservationScopesParam struct {
	value *ObservationScopesParam
	isSet bool
}

func (v NullableObservationScopesParam) Get() *ObservationScopesParam {
	return v.value
}

func (v *NullableObservationScopesParam) Set(val *ObservationScopesParam) {
	v.value = val
	v.isSet = true
}

func (v NullableObservationScopesParam) IsSet() bool {
	return v.isSet
}

func (v *NullableObservationScopesParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObservationScopesParam(val *ObservationScopesParam) *NullableObservationScopesParam {
	return &NullableObservationScopesParam{value: val, isSet: true}
}

func (v NullableObservationScopesParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObservationScopesParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
